Repository remib18/webtoon-like, pull requests merged in 2022-04, with the labels that each got.

#9 Base site
  .gitignore
  .idea/modules.xml
  site-php/.htaccess
  site-php/assets/scripts/importFormController.js
  site-php/assets/scripts/search.js
  site-php/assets/styles/app.css
  site-php/assets/styles/page-home.css
  site-php/assets/styles/page-import.css
  site-php/assets/styles/page-proposition.css
  site-php/assets/styles/page-webtoon.css
  site-php/assets/styles/reset.css
  site-php/index.php
  site-php/src/controller/AbstractController.php
  site-php/src/index.php
  site-php/src/pages/error.php
  site-php/src/pages/home.php
  site-php/src/pages/import.php
  site-php/src/pages/proposition.php
  site-php/src/pages/webtoon.php
  site-php/src/utils/Database.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
Labels: feature

#12 Base update
  .gitignore
  SETUP.md
  site-php/composer.json
  site-php/src/controller/AbstractController.php
  site-php/src/features/translationHandler.php
  site-php/src/index.php
  site-php/src/settings.php
  site-php/src/utils/Database.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
Labels: enhancement, feature

#18 Workspace configuration
  .gitignore
  .idea/dataSources.xml
  .idea/php.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
  .idea/webtoon-like.iml
Labels: documentation

#23 Update SETUP.md
  SETUP.md
Labels: documentation

#25 Feature translation
  .gitignore
  .idea/dataSources.xml
  .idea/php.xml
  .idea/sqldialects.xml
  .idea/webResources.xml
  .idea/webtoon-like.iml
  SETUP.md
  site-php/composer.json
  site-php/index.php
  site-php/src/Settings.php
  site-php/src/controller/AbstractController.php
  site-php/src/controller/ChapterController.php
  site-php/src/controller/ImageController.php
  site-php/src/controller/WebtoonController.php
  site-php/src/entities/Block.php
  site-php/src/entities/Chapter.php
  site-php/src/entities/EntityInterface.php
  site-php/src/entities/Image.php
  site-php/src/entities/Language.php
  site-php/src/entities/Report.php
  site-php/src/entities/Translation.php
  site-php/src/entities/TranslationProposition.php
  site-php/src/entities/User.php
  site-php/src/entities/Webtoon.php
  site-php/src/exceptions/AlreadyExistingRessourceException.php
  site-php/src/exceptions/ApiException.php
  site-php/src/exceptions/InvalidApiKeyException.php
  site-php/src/exceptions/InvalidProtocolException.php
  site-php/src/exceptions/InvalidRequestException.php
  site-php/src/exceptions/NoApiAvailableException.php
  site-php/src/exceptions/NotFoundException.php
  site-php/src/exceptions/SlowDownException.php
  site-php/src/exceptions/TranslationErrorException.php
  site-php/src/exceptions/UnImplementedMethodException.php
  site-php/src/exceptions/UnableToLoadImageException.php
  site-php/src/features/Import/Import.php
  site-php/src/features/Translation/APIs/GoogleApiTranslation.php
  site-php/src/features/Translation/APIs/LibreTranslateTranslation.php
  site-php/src/features/Translation/APIs/TranslationInterface.php
  site-php/src/features/Translation/OCR/OCRInterface.php
  site-php/src/features/Translation/OCR/Providers/GoogleOCR.php
  site-php/src/features/Translation/Result/Bloc.php
  site-php/src/features/Translation/Result/BlocPositionOption.php
  site-php/src/features/Translation/Result/Position.php
  site-php/src/features/Translation/Result/Result.php
  site-php/src/features/Translation/WebtoonTranslation.php
  site-php/src/features/translationHandler.php
  site-php/src/helpers/CurlHelper.php
  site-php/src/settings.php
  site-php/src/tests/GoogleOCR.test.php
  site-php/src/tests/WebtoonController.test.php
  site-php/src/tests/WebtoonTranslation.test.php
  site-php/src/tests/downloader.php
  site-php/src/utils/Database.php
  site-php/src/utils/OCRUtils.php
  site-php/src/utils/UriUtils.php
  sql/init/init-db_v0.sql
Labels: documentation, enhancement, feature, fix

#26 Petit patch. Probleme curlHelper et gestion des erreurs
  site-php/index.php
  site-php/src/Settings.php
  site-php/src/helpers/CurlHelper.php
  site-php/src/index.php
Labels: bug, enhancement

#24 fixing footer overflowing
  site-php/assets/styles/app.css
Labels: fix

#27 re-Implementation de ImageController / fix php-doc
  site-php/src/controller/ChapterController.php
  site-php/src/controller/ImageController.php
  site-php/src/controller/WebtoonController.php
Labels: enhancement

#29 Create codeStyleConfig.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: documentation, planification

#34 Change hack to PHP
  .gitattributes
Labels: bug, documentation, fix

#35 [FEATURE] Translation
  site-php/src/Settings.php
  site-php/src/controller/BlockController.php
  site-php/src/controller/ChapterController.php
  site-php/src/controller/ImageController.php
  site-php/src/controller/LanguageController.php
  site-php/src/controller/TranslationController.php
  site-php/src/controller/WebtoonController.php
  site-php/src/entities/Block.php
  site-php/src/entities/Chapter.php
  site-php/src/entities/EntityInterface.php
  site-php/src/entities/Image.php
  site-php/src/entities/Language.php
  site-php/src/entities/Report.php
  site-php/src/entities/Translation.php
  site-php/src/entities/TranslationProposition.php
  site-php/src/entities/User.php
  site-php/src/entities/Webtoon.php
  site-php/src/exceptions/NoApiAvailableException.php
  site-php/src/exceptions/NoIdOverwritingException.php
  site-php/src/exceptions/OCRAlreadyPerformedException.php
  site-php/src/exceptions/SlowDownException.php
  site-php/src/exceptions/TranslationException.php
  site-php/src/exceptions/UnsupportedLanguageException.php
  site-php/src/features/Translation/APIs/AzureTranslation.php
  site-php/src/features/Translation/APIs/GoogleApiTranslation.php
  site-php/src/features/Translation/APIs/LibreTranslateTranslation.php
  site-php/src/features/Translation/APIs/TranslationInterface.php
  site-php/src/features/Translation/OCR/OCRInterface.php
  site-php/src/features/Translation/OCR/Providers/GoogleOCR.php
  site-php/src/features/Translation/Result/Bloc.php
  site-php/src/features/Translation/Result/BlocPositionOption.php
  site-php/src/features/Translation/Result/Position.php
  site-php/src/features/Translation/Result/Result.php
  site-php/src/features/Translation/WebtoonTranslation.php
  site-php/src/helpers/CurlHelper.php
  site-php/src/tests/AzureTranslation.test.php
  site-php/src/tests/WebtoonTranslation.test.php
  site-php/src/tests/libreTranslationTest.php
  site-php/src/utils/Database.php
  site-php/src/utils/OCRUtils.php
  sql/init/init-db_v0.sql
Labels: enhancement, fix

#36 Testing simplification
  site-php/src/tests/LibreTranslation.test.php
  site-php/src/tests/tests.php
  site-php/tests.php
Labels: enhancement, fix

#37 Update README.md
  README.md
Labels: documentation

#38 [FEATURE] Translation: Implementing batch requests and other optimizations
  site-php/src/Settings.php
  site-php/src/controller/BlockController.php
  site-php/src/controller/ImageController.php
  site-php/src/exceptions/UnsupportedOperationException.php
  site-php/src/features/Translation/APIs/AzureTranslation.php
  site-php/src/features/Translation/OCR/Providers/Google/GoogleOCR.php
  site-php/src/features/Translation/OCR/Providers/Google/ResponseHandling.php
  site-php/src/features/Translation/OCR/Providers/GoogleOCR.php
  site-php/src/features/Translation/Result/Result.php
  site-php/src/features/Translation/WebtoonTranslation.php
  site-php/src/tests/GoogleOCR.test.php
  site-php/src/tests/WebtoonTranslation.test.php
  site-php/src/utils/Database.php
Labels: documentation, enhancement, fix

#40 [CORE] Router
  .gitignore
  .idea/misc.xml
  phpcs.xml
  site-php/.htaccess
  site-php/composer.lock
  site-php/google-key.json
  site-php/src/Settings.php
  site-php/src/core/Router.php
  site-php/src/core/RouterMode.php
  site-php/src/core/TemplateEngine.php
  site-php/src/entities/User.php
  site-php/src/index.php
  site-php/src/pages/php/error.php
  site-php/src/pages/php/home.php
  site-php/src/pages/php/import.php
  site-php/src/pages/php/proposition.php
  site-php/src/pages/php/webtoon.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
Labels: enhancement

#41 Edition des README.
  README.md
  SETUP.md
Labels: enhancement

#42 [Core] Router: Fix
  site-php/src/components/footer.php
  site-php/src/components/header.php
  site-php/src/core/Router.php
  site-php/src/index.php
  site-php/src/pages/php/error.php
  site-php/src/pages/php/home.php
  site-php/src/pages/php/import.php
  site-php/src/pages/php/proposition.php
  site-php/src/pages/php/webtoon.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
Labels: bug

#45 Edition read-me
  README.md
Labels: fix
