Repository remib18/webtoon-like, pull requests merged in 2022-05, with the labels that each got.

#47 Implémentation d'un système d'utilisateur simple.
  site-php/assets/styles/app.css
  site-php/assets/styles/page-login.css
  site-php/assets/styles/page-register.css
  site-php/src/controller/UserController.php
  site-php/src/core/AccessLevel.php
  site-php/src/core/Authentication.php
  site-php/src/core/Router.php
  site-php/src/entities/User.php
  site-php/src/handlers/login.php
  site-php/src/handlers/logout.php
  site-php/src/handlers/register.php
  site-php/src/index.php
  site-php/src/pageManager/LoginManager.php
  site-php/src/pageManager/RegisterManager.php
  site-php/src/pages/php/login.php
  site-php/src/pages/php/register.php
  site-php/src/utils/Database.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
Labels: feature

#49 Petit fix vis à vis du stockage de l'id en session après enregistrement,.
  site-php/src/core/Authentication.php
Labels: bug

#48 Ajout fonctionnalité remember-me
  site-php/assets/styles/page-login.css
  site-php/composer.json
  site-php/src/controller/LoginTokenController.php
  site-php/src/core/Authentication.php
  site-php/src/entities/LoginToken.php
  site-php/src/handlers/login.php
  site-php/src/handlers/logout.php
  site-php/src/pages/php/login.php
  site-php/src/utils/Database.php
  sql/init/init-db_v0.sql
Labels: feature

#50 Patch remember-me
  README.md
  site-php/src/core/Authentication.php
Labels: bug

#52 Petit fix d'erreur rare.
  site-php/src/core/Authentication.php
Labels: bug

#54 Oublie lors d'un precedent fix
  site-php/src/core/Authentication.php
  site-php/src/pageManager/LoginManager.php
  site-php/src/pageManager/RegisterManager.php
Labels: bug

#55 Verifcation des champs.
  site-php/src/core/Authentication.php
  site-php/src/entities/Block.php
  site-php/src/entities/Chapter.php
  site-php/src/entities/EntityInterface.php
  site-php/src/entities/Image.php
  site-php/src/entities/Language.php
  site-php/src/entities/LoginToken.php
  site-php/src/entities/Report.php
  site-php/src/entities/Translation.php
  site-php/src/entities/TranslationProposition.php
  site-php/src/entities/User.php
  site-php/src/entities/Webtoon.php
  site-php/src/handlers/login.php
  site-php/src/pages/php/register.php
  site-php/src/tests/DataVerification.test.php
  site-php/src/utils/DataTesting/DataField.php
  site-php/src/utils/DataTesting/DataType.php
  site-php/src/utils/DataTesting/DataVerification.php
  site-php/src/utils/Database.php
Labels: feature

#59 Options utilisateur (édition des infos, suppression de compte)
  site-php/assets/styles/.stylelintrc
  site-php/assets/styles/app.css
  site-php/assets/styles/page-changePassword.css
  site-php/assets/styles/page-deleteAccount.css
  site-php/assets/styles/page-user.css
  site-php/src/core/Authentication.php
  site-php/src/entities/User.php
  site-php/src/handlers/changeEmail.php
  site-php/src/handlers/changePassword.php
  site-php/src/handlers/changeUsername.php
  site-php/src/handlers/deleteAccount.php
  site-php/src/handlers/login.php
  site-php/src/handlers/register.php
  site-php/src/pageManager/LoginManager.php
  site-php/src/pageManager/MessageManager.php
  site-php/src/pageManager/RegisterManager.php
  site-php/src/pages/php/changePassword.php
  site-php/src/pages/php/deleteAccount.php
  site-php/src/pages/php/login.php
  site-php/src/pages/php/register.php
  site-php/src/pages/php/user.php
  site-php/src/utils/DataTesting/DataVerification.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
  sql/init/init-db_v0.sql
Labels: enhancement

#57 Ajout de valeurs par defaut.
  sql/init/init-db_v0.sql
Labels: enhancement

#61 Updated init db.
  compte_utilisateur.txt
  sql/init/init-db_v0.sql
Labels: feature

#60 Routine remplissage de BDD language.
  site-php/src/Settings.php
  site-php/src/entities/Language.php
  site-php/src/features/Translation/APIs/AzureTranslation.php
  site-php/src/index.php
  site-php/src/routine.php
  site-php/src/routine/DatabaseLoader.php
  site-php/src/utils/DataTesting/DataVerification.php
Labels: enhancement

#28 Yacine/populating data
  composer.phar
  site-php/assets/scripts/importFormController.js
  site-php/assets/scripts/search.js
  site-php/assets/styles/app.css
  site-php/assets/styles/page-home.css
  site-php/assets/styles/page-import.css
  site-php/src/Settings.php
  site-php/src/components/import/step1.php
  site-php/src/components/import/step2.php
  site-php/src/controller/ChapterController.php
  site-php/src/controller/ImageController.php
  site-php/src/controller/TranslationPropositionController.php
  site-php/src/entities/Chapter.php
  site-php/src/entities/Image.php
  site-php/src/entities/Language.php
  site-php/src/entities/Webtoon.php
  site-php/src/handlers/api/webtoons.php
  site-php/src/handlers/deleteChapter.php
  site-php/src/handlers/import-chapter.php
  site-php/src/handlers/import-webtoon.php
  site-php/src/handlers/proposition.php
  site-php/src/pageManager/ImportManager.php
  site-php/src/pageManager/PropositionManager.php
  site-php/src/pageManager/WebtoonManager.php
  site-php/src/pages/php/home.php
  site-php/src/pages/php/import.php
  site-php/src/pages/php/proposition.php
  site-php/src/pages/php/webtoon.php
  site-php/src/routine.php
  site-php/src/utils/Database.php
  site-php/src/utils/PageUtils.php
  site-php/src/utils/UriUtils.php
  sql/init/init-db_v0.sql
Labels: feature

#64 makes sure image are the right format
  site-php/assets/styles/page-webtoon.css
  site-php/src/components/import/step1.php
  site-php/src/components/import/step2.php
  site-php/src/entities/Webtoon.php
  site-php/src/pageManager/ImportManager.php
Labels: bug
